name: PMEAT Notice Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  notice:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py

      - name: Save last_notice.json
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: last_notice
          path: last_notice.json
